name: Build

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    tags:
      - v*
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: sudo apt install libunwind-dev
      if: runner.os == 'Linux'
    - name: Build
      run: cargo build --release --verbose --examples
    - name: Test
      id: test
      continue-on-error: true
      run: cargo test --release
    - name: Test (retry#1)
      id: test1
      run: cargo test --release
      if: steps.test.outcome=='failure'
      continue-on-error: true
    - name: Test (retry#2)
      run: cargo test --release
      if: steps.test1.outcome=='failure'
    - uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Build Wheel
      run: |
        pip install --upgrade maturin
        maturin build --release -o dist
    - name: Build Wheel - universal2
      env:
        DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
        SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk
        MACOSX_DEPLOYMENT_TARGET: 10.9
      run: |
        rustup target add aarch64-apple-darwin
        pip install --upgrade maturin
        maturin build --release -o dist --target universal2-apple-darwin
      if: matrix.os == 'macos-latest'
    - name: Rename Wheels
      run: |
        python3 -c "import shutil; import glob; wheels = glob.glob('dist/*.whl'); [shutil.move(wheel, wheel.replace('py3', 'py2.py3')) for wheel in wheels if 'py2' not in wheel]"
    - name: Upload wheels
      uses: actions/upload-artifact@v3
      with:
        name: wheels
        path: dist

  release:
    name: Release
    runs-on: ubuntu-latest
    if: "startsWith(github.ref, 'refs/tags/')"
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: wheels
      - name: Create GitHub Release
        uses: fnkr/github-action-ghr@v1.3
        env:
          GHR_PATH: .
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Dependencies
        run: sudo apt install libunwind-dev
        if: runner.os == 'Linux'
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Push to PyPi
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          pip install --upgrade wheel pip setuptools twine
          twine upload *
          rm *
      - uses: actions/checkout@v3
      - name: Push to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish
